spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: calendar_user
    password: calendar_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration