services:
  mysql:
    image: mysql:latest
    container_name: calendar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calendar
      MYSQL_USER: calendar_user
      MYSQL_PASSWORD: calendar_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
